// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_truncation_strategy`, `load_vocab`

List<Int64List> tokenizerBatch(
        {required List<String> textBatch,
        required BigInt maxLen,
        required bool lowercase,
        required bool stripAccents,
        required String vocabPath}) =>
    RustLib.instance.api.crateApiBertTokenizerBatch(
        textBatch: textBatch,
        maxLen: maxLen,
        lowercase: lowercase,
        stripAccents: stripAccents,
        vocabPath: vocabPath);

Int64List tokenizer(
        {required String text,
        String? text2,
        required BigInt maxLen,
        required bool lowercase,
        required bool stripAccents,
        required String vocabPath,
        required Truncation truncationStrategy}) =>
    RustLib.instance.api.crateApiBertTokenizer(
        text: text,
        text2: text2,
        maxLen: maxLen,
        lowercase: lowercase,
        stripAccents: stripAccents,
        vocabPath: vocabPath,
        truncationStrategy: truncationStrategy);

/// # Truncation strategy variants
/// Indicates if and how sequence pairs exceeding a given length should be truncated
enum Truncation {
  /// Truncate the longest sequence first
  longestFirst,

  /// Truncate only the first sequence
  onlyFirst,

  /// Truncate only the second sequence
  onlySecond,

  /// Do not truncate the sequences
  doNotTruncate,
  ;
}
